[package]
name = "stun_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
bytes = "1.5.0"
hex = "0.4.3"
log = "0.4.20"
rand = "0.8.5"
simple_logger = "4.2.0"
