[package]
name = "udp_test_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

