[package]
name = "wires_errors"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.71", features = [] }
ciborium = "0.2.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
